services:  
  keycloak_db:
    container_name: keycloak_db
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=ALh4Pn0pU7
      - POSTGRES_DB=keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      - keycloak

  keycloak:
    image: 'quay.io/keycloak/keycloak'
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_HOSTNAME: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ALh4Pn0pU7
      KEYCLOAK_ADMIN: eng_admin
      KEYCLOAK_ADMIN_PASSWORD: eng_admin
      #KC_SPI_THEME_DEFAULT: 'idea-theme'
      TZ: Europe/Rome
    depends_on:
      keycloak_db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9990']
      interval: 30s
      timeout: 10s
      retries: 3
    command: ['start-dev', '--import-realm']
    networks:
      - keycloak
    #volumes:
    #  - ./scripts/disable-theme-cache.cli:/opt/keycloak/startup-scripts/disable-theme-cache.cli
    #  - ./scripts/disable-theme-cache-ha.cli:/opt/keycloak/startup-scripts/disable-theme-cache-ha.cli
    #  - ./theme:/opt/keycloak/themes/idea-theme
volumes:
  keycloak_db:
networks:
  keycloak: