#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $DB_DEFAULT_USER --dbname $DB_DEFAULT <<-EOSQL
	CREATE USER $DB_USER WITH PASSWORD '$DB_USER_PASSWORD';
	CREATE DATABASE $DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
	ALTER DATABASE $DB_NAME OWNER TO $DB_USER;
	\c $DB_NAME $DB_USER
	GRANT ALL ON SCHEMA public TO $DB_USER;
EOSQL